required = [
  "github.com/improbable-eng/grpc-web/go/grpcwebproxy",
]

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
  version = "0.6.4"

[prune]
  go-tests = true
  unused-packages = true
